### ISSUE TITLE
Variate behavior of an element's mock if it's part of a looped scenario

### ISSUE THREAD

**Issue by r-n-aliev** [camunda/camunda-bpm-assert-scenario#34]
Without the ability to **change in-time output of mocked elements**, which are the part of a looped scenario, the test become **endless**.
How should be solved such a case with your lib?

**Comment by martinschimak** [comment]
Hi @r-n-aliev,

with a mocking library like e.g. mockito you can return other values when a method is invoked several times. We can leverage this here e.g. like this ...

``` java
when(insuranceApplication.waitsAtUserTask("UserTaskCheckApplicationUnderwriter"))
   .thenReturn((task) -> {
      assertThat(task).hasCandidateGroup("underwriter-1");
      task.complete();
   }, (task) -> {
      assertThat(task).hasCandidateGroup("underwriter-2");
      task.complete();
   });
```
