### ISSUE TITLE
dmn file cannot be read by modeller 3.3.2

### ISSUE THREAD

**Issue by javabean68** [camunda/camunda-bpm-assert-scenario#35]
Hi Martin,
this tool is what I'm be searching to organize my Camunda Tests. Well done!
I had problems reading the dmn file RiskCheck.dmn in the example app:
![image](https://user-images.githubusercontent.com/25293663/79365262-b0476d80-7f4a-11ea-97fc-d088b8a0607a.png)
By replacing the xml namespace directive with one from a new file it works:
![image](https://user-images.githubusercontent.com/25293663/79365873-8773a800-7f4b-11ea-93e5-769dcd0e992c.png)

I don't know if it is appropriate but the tests are green :-)
![image](https://user-images.githubusercontent.com/25293663/79365992-b7bb4680-7f4b-11ea-91f3-f10793b15f0e.png)

Bye
Fabio

**Comment by martinschimak** [comment]
Thank you! 🙏
